emergencyTransport/RouteFinder/urls.py
from django.conf.urls import patterns, url

from RouteFinder import views

urlpatterns = patterns('',
    #User request submission views
    url(r'^$', views.RequestList.as_view(), name='request_list'),
    url(r'add/$', views.RequestCreate.as_view(), name='request_add'),
    url(r'(?P<pk>\d+)/$', views.RequestUpdate.as_view(), name='request_update'),
    url(r'(?P<pk>\d+)/delete/$', views.RequestDelete.as_view(), name='request_delete'),

    #Planning views
    url(r'PrepareSolution/$', views.PrepareSolutionView.as_view(), name='preparation'),
    url(r'ExamineSolution/$', views.ExamineSolutionView.as_view(), name='solution'),

    #Test data
    url(r'Populatewithtest/$', views.PopulateTest, name='populate')
)

emergencyTransport/emergencyTransport/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

from RouteFinder.models import Request
from views import logout_page

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'emergencyTransport.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', logout_page),
                       
    url(r'^req/', include('RouteFinder.urls', namespace='RouteFinder')),
    url(r'^.*$', RedirectView.as_view(url='/req/', permanent=False)),
)

emergencyTransport/RouteFinder/models.py
#Django modules
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

#My modules
from CustomGeoposition.fields import GeopositionField

# Create your models here.

class Location(models.Model):
    latitude = models.DecimalField(max_digits=10, decimal_places=6)
    longitude = models.DecimalField(max_digits=10, decimal_places=6)
    
    def __unicode__(self):
        return unicode(self.latitude) + "," + unicode(self.longitude)
    def get_absolute_url(self):
        return reverse('locations-detail', kwargs={'pk': self.pk})
    

class Driver(models.Model):
    driver_name = models.CharField(max_length=50)
    source = GeopositionField()
    source_loc = models.ForeignKey(Location, related_name='sou', blank=True, null=True)
    sink = GeopositionField()
    sink_loc = models.ForeignKey(Location, related_name='sin', blank=True, null=True)
    capacity_Choices = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
    )
    capacity = models.IntegerField(choices=capacity_Choices)
    available_for_next_session = models.BooleanField(default=True)
    available_for_second_next_session = models.BooleanField(default=True)

    def __unicode__(self):
        return self.driver_name
    def get_absolute_url(self):
        return reverse('Driver-detail', kwargs={'pk': self.pk})
    

class RouteSegment(models.Model):
    driver = models.ForeignKey(Driver)

    pos_1 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_2 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_3 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_4 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_5 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_6 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_7 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_8 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_9 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_10 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_11 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_12 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_13 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_14 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_15 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_16 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_17 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_18 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_19 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)
    pos_20 = models.CommaSeparatedIntegerField(max_length=200, blank=True, null=True)

    nextSegment = models.ForeignKey("self", related_name='next', blank=True, null=True)
    lastSegment = models.ForeignKey("self", related_name='last', blank=True, null=True)
    
    def __unicode__(self):
        return unicode(self.id)
    def get_absolute_url(self):
        return reverse('routeSegment-detail', kwargs={'pk': self.pk})
    def set_fields(self, num, value):
        attname = 'pos_{0}'.format(num)
        setattr(self, attname, value)
    def get_field(self, num):
        attname = 'pos_{0}'.format(num)
        return getattr(self, attname)
    #def attrs(self):
    #    for field in self._meta.fields:
    #        yield field.name, getattr(self, field.name)
    

class Request(models.Model):
    user = models.ForeignKey(User,
                             default=User)    
    name = models.CharField(max_length=50)
    IN = 'In'
    OUT = 'Out'
    inOut_Choices = (
        (IN, 'Coming to work'),
        (OUT, 'Going home'),
    )
    inOut = models.CharField('Purpose of Journey',
                             max_length=3,
                             choices=inOut_Choices,
                             help_text="If coming to work set ideal time as shift start. If going home set ideal time as shift end.")
    home_location = GeopositionField()
    home_loc = models.ForeignKey(Location, related_name='hom', null=True, blank=True)
    work_location = GeopositionField()
    work_loc = models.ForeignKey(Location, related_name='wor', null=True, blank=True)
    ideal_time = models.DateTimeField()
    other_time = models.DateTimeField(help_text="Other end of time window.", blank=True, null=True)
    essential = models.BooleanField(default=False)
    urgent = models.BooleanField(default=False)
    comments = models.TextField(blank=True, help_text="Special requirements including extra time limits may be submitted here if necessary.")
    phone_number = models.CharField(max_length=15, blank=True)
    routeSegment = models.IntegerField(blank=True, null=True)
    earliest = models.IntegerField(blank=True, null=True )
    latest = models.IntegerField(blank=True, null=True)
    
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('req-detail', kwargs={'pk': self.pk})
    

class Time(models.Model):
    origin = models.ForeignKey(Location, related_name='first_loc')
    destination = models.ForeignKey(Location, related_name='second_loc')
    LatLongEstimate = models.DecimalField(max_digits=10, decimal_places=6, blank=True)
    GoogleEstimate = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    routeSegment = models.ForeignKey(RouteSegment, blank=True, null=True)

    def __unicode__(self):
        return unicode(self.origin) + "," + unicode(self.destination)
    def get_absolute_url(self):
        return reverse('times-detail', kwargs={'pk': self.pk})

class Parameters(models.Model):
    LatLongEstExp = models.DecimalField(max_digits=10, decimal_places = 9)
    LatLongEstMult = models.DecimalField(max_digits=10, decimal_places = 5)
    PoorWeather = models.DecimalField(max_digits=10, decimal_places = 5)

emergencyTransport/RouteFinder/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django import forms
from django.views import generic
from django.utils import timezone
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from decimal import Decimal, ROUND_HALF_UP
from django.core.management import call_command
from django.contrib.auth.models import User
import datetime


from RouteFinder.models import Request, Location, Parameters, Time, Driver, RouteSegment
from RouteFinder.forms import RequestForm
from RouteFinder.tasks import find_route

#Protected view classes that require users to be logged in

class ProtectedListView(generic.ListView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProtectedListView, self).dispatch(*args, **kwargs)

class ProtectedCreateView(generic.edit.CreateView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProtectedCreateView, self).dispatch(*args, **kwargs)

class ProtectedUpdateView(generic.edit.UpdateView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProtectedUpdateView, self).dispatch(*args, **kwargs)

class ProtectedDeleteView(generic.edit.DeleteView):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProtectedDeleteView, self).dispatch(*args, **kwargs)

# Views for general user request submitions

class RequestList(ProtectedListView):
    """Front page after user login. Displays their requests."""

    template_name = 'requests/list.html'
    context_object_name = 'users_request_list'

    def get_queryset(self):
        """Return future requests from user"""
        return Request.objects.filter(ideal_time__gte=timezone.now(), user = self.request.user.id)


class RequestCreate(ProtectedCreateView):
    """Adds new request from user, via Model Form"""

    model = Request
    fields = ['name', 'inOut', 'home_location', 'work_location', 'ideal_time', 'essential', 'urgent', 'comments']
    template_name = 'RouteFinder/request_add.html'
    success_url = '/req/'
    form_class = RequestForm

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super(RequestCreate, self).form_valid(form)


class RequestUpdate(ProtectedUpdateView):
    """Goes to filled in form of selected request."""

    model = Request
    fields = ['name', 'inOut', 'home_location', 'work_location', 'ideal_time', 'essential', 'urgent', 'comments']
    template_name = 'RouteFinder/request_add.html'
    success_url = '/req/'
    form_class = RequestForm


class RequestDelete(ProtectedDeleteView):
    """Deletes selected request."""

    model = Request
    success_url = '/req/'


#Views for administrator to start optimisation engine and examine solution

class PrepareSolutionView(ProtectedListView):
    
    template_name = 'RouteFinder/PrepareSolution.html'

    def get(self, request):
        staff_requests = request.GET.getlist('ids',[])[0].split(",")
        locationsUsed = []
        #Enter request locations into database
        earliest_ideal_time = None#datetime.datetime(year=1, month=1, day=1)
        latest_ideal_time = None#datetime.datetime(year=9999, month=1, day=1)
        for location in staff_requests:
            staff_request = Request.objects.get(pk=location)

            try:
                route_segment = RouteSegment.objects.get(pk=staff_request.routeSegment)
                route_segment.delete()
            except:
                pass
            staff_request.routeSegment = None
            
            if latest_ideal_time is None or staff_request.ideal_time > latest_ideal_time:
                latest_ideal_time = staff_request.ideal_time
            if earliest_ideal_time is None or staff_request.ideal_time < earliest_ideal_time:
                earliest_ideal_time = staff_request.ideal_time

            
            
            lat = Decimal(staff_request.home_location.latitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            lon = Decimal(staff_request.home_location.longitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            try:
                temp = Location.objects.get(latitude = lat, longitude = lon)
            except Location.DoesNotExist:
                temp = Location(latitude = lat, longitude = lon)
                temp.save()
            else:
                pass
            locationsUsed.append(temp)
            staff_request.home_loc = temp

            lat = Decimal(staff_request.work_location.latitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            lon = Decimal(staff_request.work_location.longitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            try:
                temp = Location.objects.get(latitude = lat, longitude = lon)
            except Location.DoesNotExist:
                temp = Location(latitude = lat, longitude = lon)
                temp.save()
            else:
                pass
            locationsUsed.append(temp)
            staff_request.work_loc = temp
            staff_request.save()
                    
        #Add drivers
        
        #First need to determine which drivers are available
        aStaffMember = Request.objects.get(pk=staff_requests[0])
        ATime = aStaffMember.ideal_time
        if ATime.hour > 12:
            earl = 780 #13 * 60
            late = 1500 #25 * 60
            if timezone.now().hour >= 12:
                session = "first"
            else:
                session = "second"
        else:
            earl = 60 #1 * 60
            late = 780 #13 * 60
            if timezone.now().hour > 12:
                session = "second"
            else:
                session = "first"

        earl_ideal_time = earliest_ideal_time.hour * 60 + earliest_ideal_time.minute
        late_ideal_time = latest_ideal_time.hour * 60 + latest_ideal_time.minute
        if earl_ideal_time < earl or late_ideal_time > late:
            return HttpResponse("<p>Time frame of requests doesn't fit into a single schedulling session. Please use the filter provided to select a scheduling period before starting scheduling.</p><p><a href='/admin/RouteFinder/request/'>Return to admin</a></p>")
        
        if session == "first":
            drivers = Driver.objects.filter(available_for_next_session = True)
        else:
            drivers = Driver.objects.filter(available_for_second_next_session = True)

        #Now add their associated locations
        for driver in drivers:
            lat = Decimal(driver.sink.latitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            lon = Decimal(driver.sink.longitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            try:
                temp = Location.objects.get(latitude = lat, longitude = lon)
            except Location.DoesNotExist:
                temp = Location(latitude = lat, longitude = lon)
                temp.save()
            else:
                pass
            locationsUsed.append(temp)
            driver.sink_loc = temp

            lat = Decimal(driver.source.latitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            lon = Decimal(driver.source.longitude).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)
            try:
                temp = Location.objects.get(latitude = lat, longitude = lon)
            except Location.DoesNotExist:
                temp = Location(latitude = lat, longitude = lon)
                temp.save()
            else:
                pass
            locationsUsed.append(temp)
            driver.source_loc = temp
            driver.save()

        #Estimate times between locations
        time_dict = {}
        try:
            parameters = Parameters.objects.order_by('-id')[0]
        except:
            parameters = Parameters(LatLongEstExp=0.583769, LatLongEstMult = 81.97300, PoorWeather = Decimal(1.0))
            parameters.save()
        for loc1 in locationsUsed:
            for loc2 in locationsUsed:
                if loc1.pk < loc2.pk:
                    try:
                        tim = Time.objects.get(origin = loc1, destination = loc2)
                        time_dict[tim.pk]=1
                    except Time.DoesNotExist:
                        tim = Time(origin = loc1, destination = loc2, LatLongEstimate = (Decimal(parameters.LatLongEstMult) * (((loc1.latitude - loc2.latitude) ** Decimal(2) + Decimal(0.387748) * (loc1.longitude - loc2.longitude) ** Decimal(2)) ** (Decimal(0.5) * Decimal(parameters.LatLongEstExp))).quantize(Decimal('0.000001'), rounding=ROUND_HALF_UP)))#Local cartesian projection with correction for latitude of Cardiff
                        tim.save()
                        time_dict[tim.pk]=1
                    except MultipleObjectsReturned:
                        pass
                elif loc1.pk == loc2.pk:
                    try:
                        tim = Time.objects.get(origin = loc1, destination = loc2)
                    except Time.DoesNotExist:
                        tim = Time(origin = loc1, destination = loc2, LatLongEstimate = 0, GoogleEstimate = 0)
                        tim.save()
                        #time_list.append(tim.pk) 
                    except MultipleObjectsReturned:
                        pass
                   

        #Start optimisation engine
        driver_list = [driver.pk for driver in drivers]

        find_route(staff_requests, driver_list, time_dict.keys(), earl, late)

        #call_command('process_tasks')
        
        context = {'object_list': Request.objects.filter(pk__in=staff_requests)}

emergencyTransport/RouteFinder/templates/RouteFinder/ExamineSolution.html
<!DOCTYPE html>


{% load staticfiles %}
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="{ % static 'RouteFinder/' % }css/bootstrap.css" rel="stylesheet" type="text/css"><link/>
    <script src="{% static 'RouteFinder/' %}js/bootstrap.js"></script>
    <script src='https://maps.google.com/maps/api/js?v=3'></script>
    <style>
        div.routedisplay-map {
            height: 240px;
            position: relative;
            margin: 6px 0;
            clear: both;
        }
        
        .routedisplay-results {
            position: absolute;
            z-index: 1;
            margin: 4px 0 0 0 !important;
            padding: 0 !important;
            background: white;
            border: 1px solid #eee;
            -webkit-box-shadow: 2px 2px 4px rgba(0,0,0,0.5);
            -moz-box-shadow: 2px 2px 4px rgba(0,0,0,0.5);
            box-shadow: 2px 2px 4px rgba(0,0,0,0.5);
        }

        .routedisplay-results li {
            list-style: none;
            padding: 4px 8px;
            border-top: 1px dotted #eee;
            cursor: pointer;
        }

        .routedisplay-results li:hover {
            background-color: #eee;
        }
        .routedisplay-results li:first-child {
            border-top: 0;
        }

        .gmnoprint img {
            max-width: none; 
        }
    </style>
</head>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<body>
    <div style="margin: 5% 5% 5% 5%">
        {% for driver in drivers %}
            <div>
                <p id="{{ driver.driver_name }}"> <b>Driver name:</b> {{ driver.driver_name }}</p>
                <div  id="{{ driver.driver_name }}results" >
                    {% for route_segment in route_segments %}
                        {% if route_segment.driver == driver %}
                            {% include "RouteFinder/ExamineSegment.html" with route_segments=route_segment order1=forloop.parentloop.counter0 order2=forloop.counter0 %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <script>
                $( "#{{ driver.driver_name }}" ).click(function() {
                    $( "#{{ driver.driver_name }}results" ).toggle( 0, function() {
                    });
                });
            </script>
        {% endfor %}
    </div>

</body>

emergencyTransport/RouteFinder/templates/RouteFinder/PrepareSolution.html
<h1>Selected Requests</h1>
<u1>
{% for staffMember in object_list %}
	<li>{{ staffMember.name }}</li>
{% endfor %}
</u1>

emergencyTransport/RouteFinder/templates/RouteFinder/request_add.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% load staticfiles %}
<head>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="{ % static 'RouteFinder/' % }css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <script src="{% static 'RouteFinder/' %}js/bootstrap.js"></script>
	{{ form.media }}
	<style>
		div.ex1 {
			margin: 2cm 4cm 3cm 4cm;
		}
	</style>
</head>
<body> 
	<div class="ex1" >
		<form action="" method ="post" class="form">
			{% csrf_token %}
			{% bootstrap_form form layout=''%}
			{% buttons %}
				<button type="submit" class="btn btn-primary">
					{% bootstrap_icon "star" %} Submit
				</button>
			{% endbuttons %}
		</form>
	</div>
</body>

emergencyTransport/RouteFinder/templates/RouteFinder/request_list.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% load staticfiles %}

<head>
	<style>
		div.ex1 {
			margin: 5% 5% 5% 5%;
		}
	</style>
</head>

<body>
	<div class="ex1">
		<div class="panel panel-default">
			<div class="panel-heading"><b>Future requests submitted by you</b></div>
			<div class="panel-" style="clear:both">
				<form action={% url 'RouteFinder:request_add' %} class="form" style="float:left">	
					{% buttons %}
					<button type="submit" class="btn btn-primary">
						{% bootstrap_icon "plus" %} Add request
					</button>
					{% endbuttons %}
				</form>
				<form action='/logout/' class="form" style="float:right">	
					{% buttons %}
					<button type="submit" class="btn btn-warning">
						{% bootstrap_icon "off" %} Logout
					</button>
					{% endbuttons %}
				</form>
			</div>
			{% if users_request_list %}
				<table class="table">
					<tr>
						<td><b>Staff member</b></td>
						<td><b>Reason for journey</b></td>
						<td><b>Shift start/end time</b></td>
						<td><b>Home address</b></td>
						<td><b>Work address</b></td>
						<td></td>
					</tr>
					{% for req in users_request_list %}
						<tr>
							<td><a href={% url 'RouteFinder:request_update' req.id %}>{{ req.name }}</a></td>
							<td><a href={% url 'RouteFinder:request_update' req.id %}>{{ req.get_inOut_display }}</a></td>
							<td><a href={% url 'RouteFinder:request_update' req.id %}>{{ req.ideal_time }}</a></td>
							<td><a href={% url 'RouteFinder:request_update' req.id %}>{{ req.home_location.address }}</a></td>
							<td><a href={% url 'RouteFinder:request_update' req.id %}>{{ req.work_location.address }}</a></td>
							<td>
								<form action={% url 'RouteFinder:request_delete' req.id %} method="post", class="form">
									{% csrf_token %}
									{% buttons %}
									<button type="submit" class="btn btn-danger">
										{% bootstrap_icon "trash" %} Delete request
									</button>
									{% endbuttons %}
								</form>
							</td>
						</tr>
					{% endfor %}
				</table>
			{% endif %}
		</div>
	</div>
</body>